### ISSUE TITLE
🐛 [Bug] Commit breaks TensorRT 8.2 compatibility

### ISSUE THREAD

**Issue by mfeliz-cruise** [pytorch/TensorRT#1205]
##  Bug Description

This [commit](https://github.com/pytorch/TensorRT/commit/2895fb84f7729b33d01e36e31d74dcf681cef469) seems to break compatibility with TRT 8.2. Filing this as a bug at @ncomly-nvidia 's request

## To Reproduce

1. Attempt to compile Torch-TRT with TRT 8.2 and this commit.

## Environment

> Build information about Torch-TensorRT can be found by turning on debug messages

 - Torch-TensorRT Version (e.g. 1.0.0):
 - PyTorch Version (e.g. 1.0):
 - CPU Architecture:
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source):
 - Build command you used (if compiling from source):
 - Are you using local sources or building from archives:
 - Python version:
 - CUDA version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by ncomly-nvidia** [comment]
Hi @mfeliz-cruise, after internal investigation, this not an issue with TRT minor version compatibility, but instead an artifact on how Torch-TRT interacts with different TRT versions. As you know, Torch-TRT only officially supports as single SW stack for stable releases at this time, and this case prior TRT versions cannot be supported due to the above. 

We understand this is an inconvenience which is why we will be increasing stack compatibility starting in v1.4 as described in #1009. Since we have discussed this offline I will close this bug. Please let me know if you'd like to reopen.
