### ISSUE TITLE
❓ [Question] Are the interpolate plugins with align_corners=True still necessary?

### ISSUE THREAD

**Issue by mfeliz-cruise** [pytorch/TensorRT#1437]
## What you have already tried
https://github.com/pytorch/TensorRT/blob/master/core/conversion/converters/impl/interpolate.cpp#L566
This note is in the aten::upsample_bilinear2d converter:
`Align corners and scale factor behave slightly different together in TRT and PyTorch so run the layer in ATen to maintain consistency between Torch-TensorRT and PyTorch https://pytorch.org/docs/stable/nn.functional.html#torch.nn.functional.interpolate`

With TRT 8.2.3 when I manually disable the plugin implementation and  use the TRT resize_layer implementation I don't see any additional inaccuracy in my model. I also don't see any failures in the interpolate unit tests.

Are these plugins still necessary? What was the nature of the discrepancy with align corners?

## Environment

> Build information about Torch-TensorRT can be found by turning on debug messages

 - PyTorch Version (e.g., 1.0):
 - CPU Architecture:
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source):
 - Build command you used (if compiling from source):
 - Are you using local sources or building from archives:
 - Python version:
 - CUDA version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by narendasan** [comment]
Haven't look at this recently so not sure if its still necessary but re 
> What was the nature of the discrepancy with align corners?

In ~TRT7 there was an issue with the implementation where PyTorch used one formula for the align corners case to calculate dimensions and TRT used the TF (iirc) formula causing this setting to produce different results in each. I think this was fixed in TRT 8 which is why we have the two cases.

**Comment by mfeliz-cruise** [comment]
Thanks @narendasan, this case specifically is running in TRT 8. Was this intended?
https://github.com/pytorch/TensorRT/blob/b1db33a06fe6e49004405431678946e9e8248ba8/core/conversion/converters/impl/interpolate.cpp#L566

**Comment by narendasan** [comment]
@peri044 do you know what the current status of interpolate functions are in TRT?

**Comment by peri044** [comment]
The plugins might not be necessary now I think.
@mfeliz-cruise There has been a lot of refactor and updates related to parameters around resize layers since TRT 7 and in TRT 8. 
I've disabled the plugins in upsample_bilinear2d and ran the test cases so that they use `resize_layer_size` call. They pass successfully. So, we should get away with these plugin cases and refactor interpolate.cpp
