### ISSUE TITLE
🐛 [Bug] FX front-end layer norm, missing plugin

### ISSUE THREAD

**Issue by collinmccarthy** [pytorch/TensorRT#1452]
## Bug Description

I'm using a ConvNeXt model from the timm library which uses `torch.nn.functional.layer_norm`. I'm getting this warning during conversion: 

```
Unable to find layer norm plugin, fall back to TensorRT implementation
```

which is triggered from [this line](https://github.com/pytorch/TensorRT/blob/e3b992941b3ae5f1863de271fc9032829834ec6a/py/torch_tensorrt/fx/converters/acc_ops_converters.py#L717) because it fails to find the `LayerNormDynamic` plugin. 

Do I need to install TensorRT differently from what's described in the README to install this plugin? Or where should that be installed from?

I'm following the instructions for using the pre-compiled binaries (install commands shown below).

## Environment

> Build information about Torch-TensorRT can be found by turning on debug messages

 - PyTorch Version (e.g., 1.0): 1.21.1
 - CPU Architecture: x86_64
 - OS (e.g., Linux): Ubuntu 20.04
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source): pip
 - Build command you used (if compiling from source):

```
conda install python=3.10
pip install nvidia-pyindex
pip install nvidia-tensorrt==8.4.3.1
pip install torch==1.12.1+cu116 --find-links https://download.pytorch.org/whl/torch/
pip install torch-tensorrt==1.2.0 --find-links https://github.com/pytorch/TensorRT/releases/expanded_assets/v1.2.0
```
 - Are you using local sources or building from archives: Local CUDA and cuDNN
 - Python version: 3.10
 - CUDA version: 11.6
 - GPU models and configuration: TitanV

**Comment by peri044** [comment]
I don't see a plugin named `LayerNormDynamic` in TRT plugin registry which is why we see this error. 
 Here are the plugins in TRT : https://github.com/NVIDIA/TensorRT/tree/main/plugin#contents
On the other hand, with respect to torchscript backend, we implement layernorm using native TRT layers rather than plugin.
@frank-wei  Do you know of a testcase which uses this converter https://github.com/pytorch/TensorRT/blob/e3b992941b3ae5f1863de271fc9032829834ec6a/py/torch_tensorrt/fx/converters/acc_ops_converters.py#L681

**Comment by collinmccarthy** [comment]
Any update here @peri044? I changed this from a question to a bug, because I think that's what this is (it causes the graph to be unnecessarily split when using the FX front-end, where the TS front-end keeps it as a single graph).

**Comment by frank-wei** [comment]
@collinmccarthy , we have not open sourced the plugin yet. Since it will need fx build bundle with c++ compilation. As you see, fx can be pure python now. 
But it won't stop users to use layer norm as we have vanilla version there.  https://github.com/pytorch/TensorRT/blob/e3b992941b3ae5f1863de271fc9032829834ec6a/py/torch_tensorrt/fx/converters/acc_ops_converters.py#L719

**Comment by collinmccarthy** [comment]
@frank-wei Got it, but this will split the graph and cause latency to be higher with the FX front-end than the TS front-end, correct?

**Comment by frank-wei** [comment]
> @frank-wei Got it, but this will split the graph and cause latency to be higher with the FX front-end than the TS front-end, correct? At least until the plugin is released?

No, it will not. 
The only case where graph got split is that certain layer does not have converter implementation existing.

**Comment by collinmccarthy** [comment]
Ah, okay, got it. So the latency should be similar (or the same) regardless of which front-end is used. I can test this soon.
