### ISSUE TITLE
✨[Feature] Support INT64 inputs at the graph input level

### ISSUE THREAD

**Issue by peri044** [pytorch/TensorRT#1546]
**Is your feature request related to a problem? Please describe.**
Currently if the graph is given int64 inputs, the compilation fails with unsupported type. 

**Describe the solution you'd like**
Solution we are expecting : Cast INT64 inputs to INT32 and issue a warning to users about this instead of breaking compilation.

**Describe alternatives you've considered**

**Additional context**

**Comment by gs-olive** [comment]
This feature may warrant a multi-phase detailed RFC, as it relates closely to Issue #1346, and the current (Draft) implementation can cause issues for users requiring `aten::scatter` support or other Torch-only Long-only operations. The linked PR #1551 implements autocasting in a way which is efficient (no-copying) but can break existing models due to issues with Int64-required operations, since it in-place casts input tensors for the duration of inference. I think additional design work is needed to track data types through different engines and implement an efficient casting system.

**Comment by Christina-Young-NVIDIA** [comment]
Feature split between NVP & some optional phases (detailed in RFC), trying to complete NVP for this sprint.
