### ISSUE TITLE
Error when running Resnet50-CPP.ipynb, ./torchtrt_runtime_example: symbol lookup error: ./torchtrt_runtime_example: undefined symbol: _ZN2at4_ops11randint_low4callEllN3c108ArrayRefIlEENS2_8optionalINS2_10ScalarTypeEEENS5_INS2_6LayoutEEENS5_INS2_6DeviceEEENS5_IbEE

### ISSUE THREAD

**Issue by akshayantony12** [pytorch/TensorRT#1638]
I was following this notebook on  nvcr.io/nvidia/pytorch:22.12-py3, container make runs fine but this step fails. My host has nvidia-470, 11.4. I have tried multiple times but the same error.

**Comment by peri044** [comment]
This could probably be due to pytorch version incompatibility. If you built the executable inside the container, you should run it inside the container (since it has different pytorch compared to the public 1.13 release). 
Please try to run outside the container using the dependencies for [1.3 release of Torch-TRT](https://github.com/pytorch/TensorRT/releases/tag/v1.3.0) and let us know if you still see the error.
