### ISSUE TITLE
TensorRT 8.6

### ISSUE THREAD

**Issue by johnnynunez** [pytorch/TensorRT#1848]
When will tensor 8.6 be added? On new GPU's using CUDA 12 does not work with version 8.5
https://github.com/NVIDIA/TensorRT/releases/tag/v8.6.0

**Comment by gs-olive** [comment]
We are working to switch our `main` branch over to TRT 8.6 now (PR #1852), and our upcoming release 1.4 will be based on TRT 8.6. Switching to CUDA 12 is not yet planned, since our current Torch distribution dependency does not have a CUDA 12-compatible build, but you can build Torch-TensorRT from scratch using your own Torch/CUDA versions by replacing the `libtorch`, `libtorch_pre_cxx11_abi`, and `cuda` sections in the WORKSPACE file, and rebuilding Torch-TensorRT from scratch:
https://github.com/pytorch/TensorRT/blob/1d78f436a9a423a8486338ecefd972fd08777f63/WORKSPACE#L40-L70

**Comment by johnnynunez** [comment]
> We are working to switch our `main` branch over to TRT 8.6 now (PR #1852), and our upcoming release 1.4 will be based on TRT 8.6. Switching to CUDA 12 is not yet planned, since our current Torch distribution dependency does not have a CUDA 12-compatible build, but you can build Torch-TensorRT from scratch using your own Torch/CUDA versions by replacing the `libtorch`, `libtorch_pre_cxx11_abi`, and `cuda` sections in the WORKSPACE file, and rebuilding Torch-TensorRT from scratch:
> 
> https://github.com/pytorch/TensorRT/blob/1d78f436a9a423a8486338ecefd972fd08777f63/WORKSPACE#L40-L70

Yes I have seen that they are working on CUDA 12 on the main branch. In fact they will remove cuda 11.7 to add CUDA 12.1.
https://github.com/pytorch/pytorch/pull/98832
https://github.com/pytorch/pytorch/pull/98986
https://github.com/pytorch/pytorch/pull/98398

**Comment by narendasan** [comment]
We support TRT 8.6 so closing this issue
