### ISSUE TITLE
❓ [Question] Timeline for TensorRT 9.0 support

### ISSUE THREAD

**Issue by tdeboissiere** [pytorch/TensorRT#2284]
## ❓ Question

What is the timeline to support TensorRT 9.0 ?

## What you have already tried

Using Nvidia's 9.0 TensorRT [release](https://github.com/NVIDIA/TensorRT/tree/release/9.0) is incompatible with the latest version of torch-tensorrt (which requires TensorRT 8.6).

**Comment by bowang007** [comment]
@narendasan any plan for this?

**Comment by laikhtewari** [comment]
Torch-TensorRT will not be compatible with TensorRT 9.0 since TensorRT 9.0 is designed for a restricted set of GPUs and platforms. Instead, Torch-TensorRT will stay aligned with TensorRT 8.6.1 and transition to TensorRT 10.x, scheduled for release in Q1 2024, which will offer compatibility across the full support matrix.
