### ISSUE TITLE
Failed to convert LSTM layer with dynamic batch size with TensorRT 8.6 when running torch_tensorrt on GeForce RTX 3090

### ISSUE THREAD

**Issue by AlexanderSlav** [pytorch/TensorRT#2314]
# Description

I am trying to convert a CRNN model with a dynamic batch size and width, but I encountered an error during the conversion process. After some debugging, I was able to localize the problem: the conversion fails when it reaches the LSTM layer using Torch-TensorRT with a dynamic batch size setup.

To further investigate, I created a separate script to convert just the LSTM layer and encountered a runtime error during the compilation process. Specifically, the process fails with the following message:

` Trying to create tensor with negative dimension -1: [1, -1, 256].`

Is dynamic batch size not supported for LSTM models or maybe i do something incorrect ?
It seems that LSTM by itself  is supported with torch_tensorrt or am i wrong ?

## Code to Reproduce

Here is the code snippet that I used for conversion:

```

import torch
import torch_tensorrt
import torch.nn as nn

class RecurrentLayer(nn.Module):
    def __init__(self, input_channels: int, output_channels: int):
        super(RecurrentLayer, self).__init__()
        self._rnn = nn.LSTM(input_channels, output_channels)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        y, _ = self._rnn(x)
        return y


def main():
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model = RecurrentLayer(256, 256)
    model = model.eval().to(device)

    input_data = torch.randn(32, 20, 256).to(device)
    model = torch.jit.trace(model, input_data)

    # L, N, H_in the input shape match LSTM input description
    # N - batch size 
    # L - sequence length
    # H_in - input_size
    
    min_shape=[32, 20, 256]
    opt_shape=[64, 40, 256]
    max_shape=[128, 60, 256]

    fp16 = False

    trt_model = convert_with_torch_tensorrt(model, min_shape, opt_shape, max_shape, fp16)
    _ = trt_model(input_data)
    torch.jit.save(trt_model, "/workdir/rnn_separately.pt")

def convert_with_torch_tensorrt(model, min_input_shape, opt_input_shape, max_input_shape, fp16):
    enabled_precisions = torch.float16 if fp16 else torch.float32

    # Dynamic shapes for the input
    input_spec = torch_tensorrt.Input(
        min_shape=min_input_shape,
        opt_shape=opt_input_shape,
        max_shape=max_input_shape,
        dtype=enabled_precisions,
    )

    with torch_tensorrt.logging.debug():
        trt_model = torch_tensorrt.compile(
            module=model,
            inputs=[input_spec],
            enabled_precisions=[enabled_precisions],
            truncate_long_and_double=True,
        )
    return trt_model

if __name__ == "__main__":
    main()
```

Error log after running the script in the attachment

[error_log_traced_model.txt](https://github.com/NVIDIA/TensorRT/files/12577066/error_log_traced_model.txt)

I also tried replace `torch.jit.trace` with `torch.jit.script ` and it gives me:

`WARNING: [Torch-TensorRT] - Didn't generate any TensorRT engines, the compiler did nothing`

Error log also in attachment.
[error_log_scripted_model.txt](https://github.com/NVIDIA/TensorRT/files/12577065/error_log_scripted_model.txt)

## Environment

For developing i use following docker image [dokai:23.05-pytorch](https://github.com/osai-ai/dokai#pytorch)

**TensorRT Version**: 8.6.1

**NVIDIA GPU**: GeForce RTX 3090

**NVIDIA Driver Version**: 530.30.02

**CUDA Version**:  12.1

**CUDNN Version**:  release 11.8, V11.8.89

## Operating System:

Python Version: Python 3.10.6

PyTorch Version:  2.0.0a0+gite9ebda2

Baremetal or Container: docker image [dokai:23.05-pytorch](https://github.com/osai-ai/dokai#pytorch)

### Expected Behavior
I expect the code to successfully convert the LSTM model with dynamic batch sizes

### Actual Behavior
I get a runtime error with the message `Trying to create tensor with negative dimension -1: [1, -1, 256].`

**Comment by narendasan** [comment]
@gs-olive can you try this with torch.compile?

**Comment by gs-olive** [comment]
Hello - I am able to reproduce this issue in the TorchScript path on the latest `main`.

### The Issue in TorchScript
Since the JIT graph contains an `aten::size` operator applied to a Dynamically-shaped tensor, the compilation fails. I also tried with `allow_shape_tensors=True`, but this results in an `IValue` unwrapping error when evaluating `aten::zeros` with a ShapeTensor.

### Potential Workaround in TorchScript
It is worth noting that we do not currently have a TorchScript converter for `aten::lstm`, but we do have a converter for `aten::lstm_cell`, so if the implementation could be refactored to use `nn.LSTMCell`, then it is possible that the compilation could succeed in TorchScript.

### Torch Compile Path
I also tested out this model with our `torch.compile` backend, and the model does successfully compile, with the only missing operator being `torch.ops.aten.unbind.int`. In order to get compilation going, one has to specify `torch._dynamo.config.allow_rnn = True` at the top of the file, otherwise Dynamo will not trace `nn.LSTM` modules. In this case, the call was:
```python
torch._dynamo.config.allow_rnn = True

...

    trt_model = torch_tensorrt.compile(
        module=model,
        ir="torch_compile",
        inputs=[input_spec],
        enabled_precisions=[enabled_precisions],
        truncate_long_and_double=True,
        debug=True,
    )
```

The limitation of the above for this specific use case is that the model cannot be serialized between sessions yet. The Dynamo export (`ir="dynamo"`) path is not currently functional for this model since `aten._cudnn_rnn_flatten_weight.default` is not supported in tracing. See this related issue: https://github.com/pytorch/pytorch/issues/91439.

**Comment by AlexanderSlav** [comment]
Hi, thanks for replay
I tested your workaround with LSTMCell and adapted RecurrentLayer code
The rest code stayed the same

```
class RecurrentLayer(nn.Module):
    def __init__(self, input_channels: int, output_channels: int):
        super(RecurrentLayer, self).__init__()
        self._rnn_cell = nn.LSTMCell(input_channels, output_channels)
        self.output_channels = output_channels

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        seq_len, batch_size, _ = x.size()
        h_0 = torch.zeros(batch_size, self.output_channels).to(x.device)
        c_0 = torch.zeros(batch_size, self.output_channels).to(x.device)

        outputs = []

        for i in range(seq_len):
            h, c = self._rnn_cell(x[i], (h_0, c_0))
            outputs.append(h)

        return torch.stack(outputs, dim=0)
```

But still got the same error 

```
DEBUG: [Torch-TensorRT TorchScript Conversion Context] - Freezing tensor 0x5621956fbc48 as an IConstantLayer
DEBUG: [Torch-TensorRT] - Gather tensor shape: [1, -1, 256]
DEBUG: [Torch-TensorRT] - Output tensor shape: [1, 256]
DEBUG: [Torch-TensorRT TorchScript Conversion Context] - Evaluating %65 : int = aten::size(%x, %4) # /workdir/test_separate_conversion.py:21:0
WARNING: [Torch-TensorRT] - There may be undefined behavior using dynamic shape and aten::size without setting allow_shape_tensors
DEBUG: [Torch-TensorRT TorchScript Conversion Context] - Found the value to be: -1
DEBUG: [Torch-TensorRT TorchScript Conversion Context] - Evaluating %66 : int[] = prim::ListConstruct(%65, %67)
DEBUG: [Torch-TensorRT TorchScript Conversion Context] - Found the value to be: [-1, 256]
DEBUG: [Torch-TensorRT TorchScript Conversion Context] - Evaluating %68 : Tensor = aten::zeros(%66, %69, %69, %70, %71) # /workdir/test_separate_conversion.py:22:0
Traceback (most recent call last):
  File "/workdir/test_separate_conversion.py", line 71, in <module>
    main()
  File "/workdir/test_separate_conversion.py", line 47, in main
    trt_model = convert_with_torch_tensorrt(model, min_shape, opt_shape, max_shape, fp16)
  File "/workdir/test_separate_conversion.py", line 62, in convert_with_torch_tensorrt
    trt_model = torch_tensorrt.compile(
  File "/usr/local/lib/python3.10/dist-packages/torch_tensorrt/_compile.py", line 133, in compile
    return torch_tensorrt.ts.compile(
  File "/usr/local/lib/python3.10/dist-packages/torch_tensorrt/ts/_compiler.py", line 139, in compile
    compiled_cpp_mod = _C.compile_graph(module._c, _parse_compile_spec(spec))
RuntimeError: Trying to create tensor with negative dimension -1: [-1, 256]
```

**Comment by gs-olive** [comment]
Thank you for testing this out. I looked into the graph produced and it seems that Torch lowers the `nn.LSTMCell` to `aten::_thnn_fused_lstm_cell`, which we do not currently support. Given this, I do not think there is a benefit to using the `LSTMCell` over the plan `LSTM` currently.

Additionally, with this new model format, the error is now clearer. The issue arises from the line `h_0 = torch.zeros(batch_size, self.output_channels).to(x.device)`, where `batch_size` is dynamic, and we attempt to instantiate a tensor of dynamic size. This one would be a challenging case for dynamic shape, since `aten::zeros` is an evaluator, dispatched at compile-time. A temporary workaround for this is to include the argument `torch_executed_ops=["aten::zeros"]` in your compilation call.
