### ISSUE TITLE
Windows CI for Python-Only Implementation

### ISSUE THREAD

**Issue by gs-olive** [pytorch/TensorRT#2489]
- Get CI up and running for Windows implementation using only the Python runtime

**Comment by gs-olive** [comment]
Windows build is now successful with this branch: [`windows_CI`](https://github.com/pytorch/TensorRT/tree/windows_CI), however the smoke-test fails due to a missing `.dll` file, [as here](https://github.com/pytorch/TensorRT/actions/runs/7280075715/job/19864883942?pr=2502)

**Comment by HolyWu** [comment]
Actually `cudnn_adv_train64_8.dll` exists in that directory and isn't missing. The reason is that `tensorrt` and `torch` load their own cuDNN DLLs and the version conflicts. Until the PyTorch devs upgrade the bundled cuDNN version from 8.8 to 8.9 in the windows wheel, the only workaround I can think of is to manually copy the DLLs from `site-packages/nvidia/cudnn/bin` to `site-packages/torch/lib` and overwrites them.

**Comment by gs-olive** [comment]
@HolyWu - thank you for the suggestion on this. I will try out the manual copy in the smoke test to get the CI tests running in the meantime.
