### ISSUE TITLE
❓ [Question] why not set user defined dtype

### ISSUE THREAD

**Issue by Xseventh** [pytorch/TensorRT#681]
i see it don't do anything when user defined dtype
https://github.com/NVIDIA/TRTorch/blob/master/core/compiler.cpp#L339

**Comment by narendasan** [comment]
The user has set the value of dtype explicitly so we dont need to go in and look at the graph to determine what type we should expect. TRTorch's default behavior is to use the PyTorch convention that input tensors and weight tensors need to be the same type. Therefore we can infer the input type from the weight type. But we leave the option open if the user wants to override this behavior and set the dtype field explicitly. So in that case we just use the Input spec give instead of modifying it.
